vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number relativenumber")
vim.cmd("set numberwidth=1")
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set('t', 'jk', [[<C-\><C-n>]])
vim.keymap.set('t', '<esc>', [[<C-\><C-n>]])
vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]])
vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]])
vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]])
vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]])
vim.keymap.set('t', '<C-w>', [[<C-\><C-n><C-w>]])
vim.keymap.set({"n","i"}, "<A-h>", '<Cmd>:bp<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<A-l>", '<Cmd>:bn<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<A-j>", '<Cmd>:bd<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<F3>", '<Cmd>::ToggleTermToggleAll<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<F4>", '<Cmd>:ToggleTerm size=20 dir="./" direction=horizontal<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<F5>", '<Cmd>:wa<CR><Cmd>:TermExec cmd="cargo run --release" dir="./" size=30 direction="horizontal"<CR>', { noremap = true})
vim.keymap.set({"n","i"}, "<F6>", '<Cmd>:wa<CR><Cmd>:TermExec cmd="cargo test -- --nocapture" dir="./" size=30 direction="horizontal"<CR>', { noremap = true})
